### PR TITLE
Update m131023_165214_initial.php

### PR DESCRIPTION
**Pull request by Felli**
Change `notNull` to `not Null`.

### Reasons
- `notNull` is used in JAVA not PHP

### CODE REVIEW

**Comment by githubjeka** [comment]
Hmm, I'm too shy to ask.... What is it ?

**Comment by githubjeka** [comment]
@Felli 

image

**Comment by Felli** [comment]
My bad, would seem that I messed up with this one `IS NOT NULL` is the proper way of doing this...

http://www.sqlteam.com/forums/topic.asp?TOPIC_ID=105509

**Comment by githubjeka** [comment]
Stop it ) 

This code is not native sql, this PHP and Yii2 feature. See migration documentation please http://www.yiiframework.com/doc-2.0/guide-db-migrations.html and [API code](http://www.yiiframework.com/doc-2.0/yii-db-schemabuildertrait.html)

**Comment by solracsf** [comment]
`notNull()` is a public method and it adds a `NOT NULL` constraint to the column.

**Pull request closed without merging**
